### ISSUE TITLE
Sensitive Information

### ISSUE THREAD

**Issue by billthebuilder** [TabithaKavyu/Second-Year-Project#1]
- I've observed sensitive information exposed in `authenticate.php` like database logins, usernames
- Try using environment variables instead

**Comment by StanleyMasinde** [comment]
Or use a config file that is not tracked by git.

Example `config.php` the configuration can take the form of an associative array

```php
$config = [
  "DB_HOST": ""
]
```

Because you are not committing this file, you can have a `config.example` file with the entries without values

Another option is to use dotenv() library......

**Comment by conradKE** [comment]
add the link to .gitignore when commiting

**Comment by StanleyMasinde** [comment]
@BILLthebuilder close this issue inajaza issues kwa dashboard bure

**Comment by billthebuilder** [comment]
> @BILLthebuilder close this issue inajaza issues kwa dashboard bure

Huyu aliignore

**Comment by StanleyMasinde** [comment]
> > @BILLthebuilder close this issue inajaza issues kwa dashboard bure
> 
> Huyu aliignore

Yes funga hii kitu 🤣
